---
title: "Diamond Plots"
author: "Gjalt-Jorn Ygram Peters"
date: "`r format(Sys.time(), '%Y-%m-%d at %X');`"
output: html_document
---

```{r setup, include=FALSE}

########################################################################
### Paths
########################################################################

### Add any relevant paths to this vector. The script will select the
### correct path itself.

basePathVector <- c('B:/Data/research',
                    '');

########################################################################
### Set the variables with the paths
########################################################################

### Check which paths exist and set the first existing path in the list
### as the base path
basePath <- basePathVector[sapply(basePathVector, dir.exists)][1];

### Set the additional paths
outputPath <- file.path(basePath, 'determinant-importance');
dataPath <- file.path(basePath, 'party panel', '15.1', 'data');
dataFileName <- 'survey_652829_R_data_file.csv';
dataLoadScriptName <- 'survey_652829_R_syntax_file.R';

knitr::opts_chunk$set(echo = FALSE);

if (!require('userfriendlyscience')) {
  stop("You need to have package 'userfriendlyscience' installed!");
}
safeRequire('ggplot2');
safeRequire('grid');
safeRequire('data.tree');
safeRequire('pander');

### Enable automatic figure caption numbering
setFigCapNumbering();

```

```{r preparation}

### Import data from LimeSurvey data file
dat <- importLimeSurveyData(datafile = file.path(dataPath, dataFileName),
                            scriptfile = file.path(dataPath, dataLoadScriptName),
                            categoricalQuestions = c('informedConsent',
                                                     'gender',
                                                     'hasJob',
                                                     'currentEducation',
                                                     'prevEducation',
                                                     'country'));

### Remove one case threatening data integrity
dat <- dat[is.na(dat$age) | dat$age < 100, ];

### Set age to NA for those who did not want to provide their age
dat$age <- ifelse(dat$age==0, NA, dat$age);

### Rename one inconsistently named variable
names(dat)[names(dat) == 'highDose_AttBeliefs_intensity'] <- 'highDose_AttBeliefs_intens';

### Create a set of three regular expressions to add
### underscores behind the behaviors
varnameRegExPairs <- lapply('highDose', function(curBehav) {
  return(c(paste0("^", curBehav, "(.+)"),
           paste0(curBehav, "_\\1")));
});

### Process the variables labels (subquestions, anchors etc)
dat.labelDf <- processLSvarLabels(dat, varnameRegExPairs = varnameRegExPairs);

### Replace variable names with the versions with the
### inserted underscores
names(dat) <- dat.labelDf$varNames.cln;

### Specify the determinant structure
detStruct <-
   determinantStructure('highDose',
                        list('highDose',
                             behaviorRegEx = 'highDose'),
                             determinantVar("intention",
                                            "IntentionRAA",
                                            determinantVar("attitude",
                                                           "AttGeneral",
                                                           subdeterminants("Likelihood",
                                                                           "AttBeliefs"))));

### Process the determinant structure, eventually ordering the
### determinant importance plots

### Add variable names to the determinant structure object
detStructAddVarNames(detStruct,
                     names = grep("\\.\\.", names(dat), value=TRUE, invert=TRUE));
### Compute scales
dat <- detStructComputeScales(detStruct, dat);
### Add variable labels
detStructAddVarLabels(detStruct, dat.labelDf);

### Extract variable labels and translate them
subQuestions.original <- detStruct$intention$attitude$Likelihood$subQuestions;
leftAnchors.original <- detStruct$intention$attitude$Likelihood$leftAnchors;
rightAnchors.original <- detStruct$intention$attitude$Likelihood$rightAnchors;

translations <- matrix(
  c("If I use a high dose of ecstasy,\nmy trip is...", "shorter", "longer",
    "If I use a high dose of ecstasy,\nmy trip is...", "more mild", "more intense",
    "If I use a high dose of ecstasy,\nI get...", "much less\nintoxicated", "much more\nintoxicated",
    "A high dose of ecstasy gives me...", "much less\nenergy", "much more\nenergy",
    "With a high dose of ecstasy,\nthe happy, euphoric feeling is...", "much weaker", "much stronger",
    "If I use a high dose of ecstasy,\nI learn...", "much less\nabout myself", "much more\nabout myself",
    "If I use a high dose of ecstasy,\nI feel...", "much less\nconnected\n to others", "much more\nconnected\nto others",
    "If I use a high dose of ecstasy,\nI can make contact with others...", "much harder", "much easier",
    "If I use a high dose of ecstasy,\nI feel like having sex...", "much less", "much more",
    "If I use a high dose of ecstasy,\nI forget my problems...", "much slower", "much faster",
    "If I use a high dose of ecstasy,\nI feel...", "much less\nself-absorbed", "much more\nself-absorbed",
    "With a high dose of ecstasy,\nI can test my boundaries...", "much less", "much better",
    "If I use a high dose of ecstasy,\nthe music sounds...", "much worse", "much better",
    "If I use a high dose of ecstasy,\nI hallucinate...", "much less", "much more",
    "If I use a high dose of ecstasy,\nI feel time passes...", "much slower", "much faster",
    "If I use a high dose of ecstasy,\nafterwards I remember...", "much less", "much more",
    "For my health, using a high\ndose of ecstasy is...", "much worse", "much better",
    "My experience with using a high\ndose of ecstasy is...", "worse", "better",
    "Do you worry as much, more, or less\nabout the physical side effects of\nusing a high dose of ecstasy?", "worry\nmuch less", "worry\nmuch more",
    "Do you worry as much, more, or less\nabout the emotional and psychic side\neffects of using a high dose of ecstasy?", "worry\nmuch less", "worry\nmuch more",
    "Do you have as much, more, or less\nregret after using a high dose of ecstasy?", "much less\nregret", "much more\nregret"), ncol=3, byrow=TRUE);

subQuestions.translated <- translations[, 1];
leftAnchors.translated <- translations[, 2];
rightAnchors.translated <- translations[, 3];

subQuestions <- subQuestions.translated;
leftAnchors <- leftAnchors.translated;
rightAnchors <- rightAnchors.translated;


selectedVariables <- 12:18;
selectedVarNames <- unlist(detStruct$intention$attitude$Likelihood$varNames)[selectedVariables];

varLabels <- c("A high dose causes more hallucinations",
               "A high dose makes time pass faster",
               "A high dose improves my memory",
               "A high dose is better for my health",
               "A high dose yields a better experience");

meansDiamondPlot(dat, selectedVarNames,
                 showData=FALSE);

meansDiamondPlot(dat, selectedVarNames,
                 showData=FALSE) +
  xlim(1, 7);

meansDiamondPlot(dat, selectedVarNames);

meansDiamondPlot(dat, selectedVarNames, labels=varLabels);

biAxisDiamondPlot(dat, selectedVarNames,
                  leftAnchors[selectedVariables],
                  rightAnchors[selectedVariables],
                  subQuestions=subQuestions[selectedVariables]);




associationsDiamondPlot(dat, selectedVarNames, detStruct$intention$scaleVarName);

associationsDiamondPlot(dat, selectedVarNames,
                        detStruct$intention$scaleVarName,
                        alpha=.5, color = 'blue') +
  associationsDiamondPlot(dat, selectedVarNames,
                          detStruct$intention$attitude$scaleVarName,
                          alpha=.5, color='red',
                          returnLayerOnly = TRUE);

### Set 'other' gender to NA
dat$gender <- factor(ifelse(as.numeric(dat$gender) > 1 &
                            as.numeric(dat$gender) < 4,
                            dat$gender, NA),
                     labels=c('Male', 'Female'));

associationsDiamondPlot(dat, selectedVarNames, 'gender');
associationMatrix(dat, selectedVarNames, 'gender');

associationMatrix(dat, 'gender', 'age');



```
